config/routes.rb
SEOManagerAA::Application.routes.draw do
  mount RailsAdmin::Engine => '/railsadmin', :as => 'rails_admin'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :websites
end

app/models/website.rb
class Website < ActiveRecord::Base
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    #redirect_to admin_dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.navigation{:style =>"padding:30px"}
  %h1
    SEO MANAGER
  =link_to "Active Admin",admin_dashboard_path
  %p
    admin@example.com / password
  =link_to "Rails Admin", rails_admin_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SEOManagerAA</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>